# Generated by Django 5.2 on 2025-04-19 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_topic_owner'),
        ('learning_logs', '0003_topic_owner'),
    ]

    operations = [
    ]
